

class HectorPacket:
    JOYSTICK_RESERVE_START = 4
    JOYSTICK_RESERVE_END = 24

    CLIENT_ID_BYTE = 0
    HECTOR_MODE_BYTE = 1

    JOYSTICK_LEFT_Y = 4
    JOYSTICK_LEFT_X = 5

    JOYSTICK_RIGHT_Y = 6
    JOYSTICK_RIGHT_X = 7

