
class HectorMap:

    PAN_DIRECTION_PIN = 5
    PAN_STEP_PIN = 6

    TILT_DIRECTION_PIN = 26
    TILT_STEP_PIN = 30

    DRIVETRAIN_LEFT_FWD = 19
    DRIVETRAIN_LEFT_BKWD = 26

    DRIVETRAIN_RIGHT_FWD = 13
    DRIVETRAIN_RIGHT_BKWD = 17
