
class HectorMap:

    PAN_DIRECTION_PIN = 23
    PAN_STEP_PIN = 24

    TILT_DIRECTION_PIN =27
    TILT_STEP_PIN = 4

    DRIVETRAIN_LEFT_FWD = 19
    DRIVETRAIN_LEFT_BKWD = 26

    DRIVETRAIN_RIGHT_FWD = 13
    DRIVETRAIN_RIGHT_BKWD = 17

    LASER_DIGITAL_OUT = 22
