class HectorMap:
    PAN_DIRECTION_PIN = 23
    PAN_STEP_PIN = 24

    TILT_DIRECTION_PIN = 27
    TILT_STEP_PIN = 4

    DRIVETRAIN_LEFT_FWD = 11
    DRIVETRAIN_LEFT_BKWD = 9

    DRIVETRAIN_RIGHT_FWD = 8
    DRIVETRAIN_RIGHT_BKWD = 10

    LASER_DIGITAL_OUT = 22